program patch_doc;
{$mode objfpc}{$H+}
// The module reference, GENERATED FROM THE REGISTRY.
//
// Written by hand it would diverge from the code within a month: a port added,
// a default changed, a range widened, and the documentation quietly starts
// lying. Here every row is produced by instantiating the module and asking it,
// so the reference cannot be wrong — at worst it is missing something that has
// no port, and those are listed too.
//
//   bin/<plat>/patch_doc            -> Markdown on stdout
//   bin/<plat>/patch_doc --plain    -> a plain table, easier to read in a shell
uses
  SysUtils, Classes, SedaiPatchGraph, SedaiPatchModules, SedaiPatchElectronic,
  SedaiPatchInstruments, SedaiPatchPart, SedaiPatchSpace, SedaiPatchBody,
  SedaiPatchLegacy;

var
  GMarkdown: Boolean = True;

function MakeModule(const AType: string): TSedaiPatchModule;
begin
  Result := CreateModuleByType(AType);
  if Result = nil then Result := CreateElectronicModuleByType(AType);
  if Result = nil then Result := CreateInstrumentModuleByType(AType);
  if Result = nil then Result := CreatePartModuleByType(AType);
  if Result = nil then Result := CreateSpaceModuleByType(AType);
  if Result = nil then Result := CreateBodyModuleByType(AType);
  if Result = nil then Result := CreateLegacyModuleByType(AType);
end;

function RoleName(ARole: TSedaiPortRole): string;
begin
  case ARole of
    prAudio:    Result := 'audio';
    prPitch:    Result := 'pitch';
    prGate:     Result := 'gate';
    prUnipolar: Result := '0..+';
    prBipolar:  Result := '-..+';
  else          Result := '?';
  end;
end;

function Num(V: Single): string;
begin
  if V <= -1.0e29 then Exit('-inf');
  if V >=  1.0e29 then Exit('+inf');
  if Abs(V - Round(V)) < 1.0e-6 then Exit(IntToStr(Round(V)));
  Result := FormatFloat('0.####', V);
end;

procedure DumpType(const AType: string);
var
  M: TSedaiPatchModule;
  P: TSedaiPatchPort;
  I: Integer;
  Ins, Outs, Rate, Keys: string;
begin
  M := MakeModule(AType);
  if M = nil then Exit;
  try
    M.Prepare(44100, 128);
    if M.Rate = mrBlockOnly then Rate := 'block' else Rate := 'both';
    Ins := ''; Outs := '';
    for I := 0 to M.PortCount - 1 do
    begin
      P := M.Port(I);
      if P.Kind = pkInput then
      begin
        if Ins <> '' then Ins := Ins + ', ';
        Ins := Ins + P.Name + ' [' + RoleName(P.Role) + ' ' + Num(P.Value);
        if (P.Min > -1.0e29) or (P.Max < 1.0e29) then
          Ins := Ins + ' ' + Num(P.Min) + '..' + Num(P.Max);
        Ins := Ins + ']';
      end
      else
      begin
        if Outs <> '' then Outs := Outs + ', ';
        Outs := Outs + P.Name;
      end;
    end;
    if Ins = '' then Ins := '—';
    if Outs = '' then Outs := '—';
    Keys := M.ConfigKeys;
    if Keys = '' then Keys := '—';
    if GMarkdown then
      WriteLn('| `', AType, '` | ', Rate, ' | ', Keys, ' | ', Ins, ' | ', Outs, ' |')
    else
    begin
      WriteLn('  ', AType, '   (', Rate, ')');
      WriteLn('     keys: ', Keys);
      WriteLn('     in  : ', Ins);
      WriteLn('     out : ', Outs);
    end;
  finally
    M.Free;
  end;
end;

procedure DumpGroup(const ATitle, AList: string);
var
  Parts: TStringArray;
  I: Integer;
  T: string;
begin
  WriteLn;
  if GMarkdown then
  begin
    WriteLn('### ', ATitle);
    WriteLn;
    WriteLn('| type | rate | declaration keys | inputs `[role default min..max]` | outputs |');
    WriteLn('|---|---|---|---|---|');
  end
  else
    WriteLn('=== ', ATitle, ' ===');
  Parts := AList.Split([','], TStringSplitOptions.ExcludeEmpty);
  for I := 0 to High(Parts) do
  begin
    T := Trim(Parts[I]);
    // "inst (instrument=... )" carries its own help text in the list
    if Pos(' ', T) > 0 then T := Copy(T, 1, Pos(' ', T) - 1);
    DumpType(T);
  end;
end;

begin
  GMarkdown := (ParamStr(1) <> '--plain');
  if GMarkdown then
  begin
    WriteLn('<!-- GENERATED BY patch_doc — do not edit by hand.');
    WriteLn('     Regenerate with: bin/<plat>/patch_doc >> library/patches/README.md -->');
    WriteLn;
    WriteLn('Every row below is produced by building the module and asking it, so it');
    WriteLn('cannot drift from the code. `rate` says whether the module may sit inside a');
    WriteLn('feedback cycle: `both` may, `block` may not and the patch refuses to compile');
    WriteLn('if you try. Inputs show their role, the value they hold when nothing is');
    WriteLn('patched in, and the range they clamp to.');
  end;
  DumpGroup('Core', KnownModuleTypes);
  DumpGroup('Electronic', KnownElectronicTypes);
  DumpGroup('Instruments', KnownInstrumentTypes);
  DumpGroup('Instrument library', KnownPartTypes);
  DumpGroup('Space', KnownSpaceTypes);
  DumpGroup('Body', KnownBodyTypes);
  DumpGroup('Bridged from SAF units', KnownLegacyTypes);
  WriteLn;
end.
